### ISSUE TITLE
Issues Building

### ISSUE THREAD

**Issue by dattmavis** [keinsell/neuronek#406]
I've attempted to build the Docker release of this, and also attempted to just build it locally here on my machine. 
It appears the Readme is out of date, as commit notes indicate a move to pnpm, but the directions reference yarn.

Using Docker, I get some various errors in deployment which I'll happily share, and building locally I get the following:

`│ @sentry/profiling-node: Compiling from source...
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.3.1
│ gyp info using node@21.5.0 | linux | x64
│ gyp info find Python using Python version 3.11.6 found at "/usr/bin/python3"
│ gyp http GET https://nodejs.org/download/release/v21.5.0/node-v21.5.0-headers.tar.gz
│ gyp http 200 https://nodejs.org/download/release/v21.5.0/node-v21.5.0-headers.tar.gz
│ gyp http GET https://nodejs.org/download/release/v21.5.0/SHASUMS256.txt
│ gyp http 200 https://nodejs.org/download/release/v21.5.0/SHASUMS256.txt
│ gyp info spawn /usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/root/neuronek/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/root/neuronek/node_modules/.pnpm/@sentry+profiling-node@0.2.2/node_modules/@sentry/profiling-node/buil…
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/root/neuronek/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/root/.cache/node-gyp/21.5.0/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/21.5.0',
│ gyp info spawn args   '-Dnode_gyp_dir=/root/neuronek/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/21.5.0/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/root/neuronek/node_modules/.pnpm/@sentry+profiling-node@0.2.2/node_modules/@sentry/p…
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp info ok 
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.3.1
│ gyp info using node@21.5.0 | linux | x64
│ gyp ERR! build error 
│ gyp ERR! stack Error: not found: make
│ gyp ERR! stack     at getNotFoundError (/root/neuronek/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:10:17)
│ gyp ERR! stack     at /root/neuronek/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:57:18
│ gyp ERR! stack     at new Promise (<anonymous>)
│ gyp ERR! stack     at step (/root/neuronek/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:54:21)
│ gyp ERR! stack     at /root/neuronek/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:71:22
│ gyp ERR! stack     at new Promise (<anonymous>)
│ gyp ERR! stack     at subStep (/root/neuronek/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:69:33)
│ gyp ERR! stack     at /root/neuronek/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:80:22
│ gyp ERR! stack     at /root/neuronek/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/index.js:42:5
│ gyp ERR! stack     at /root/neuronek/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/mode.js:8:5
│ gyp ERR! System Linux 6.2.10-arch1-1
│ gyp ERR! command "/usr/bin/node" "/root/neuronek/node_modules/.pnpm/node-gyp@9.3.1/node_modules/node-gyp/bin/node-gyp.js" "bui…
│ gyp ERR! cwd /root/neuronek/node_modules/.pnpm/@sentry+profiling-node@0.2.2/node_modules/@sentry/profiling-node
│ gyp ERR! node -v v21.5.0
│ gyp ERR! node-gyp -v v9.3.1
│ gyp ERR! not ok 
│ @sentry/profiling-node: Failed to build from source, please report this a bug at https://github.com/getsentry/profiling-node/i…
│ /root/neuronek/node_modules/.pnpm/@sentry+profiling-node@0.2.2/node_modules/@sentry/profiling-node/scripts/check-build.js:51
│   throw e;
│   ^
│ Error: Cannot find module '/root/neuronek/node_modules/.pnpm/@sentry+profiling-node@0.2.2/node_modules/@sentry/profiling-node/…
│ Require stack:
│ - /root/neuronek/node_modules/.pnpm/@sentry+profiling-node@0.2.2/node_modules/@sentry/profiling-node/scripts/check-build.js
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
│     at Module._load (node:internal/modules/cjs/loader:984:27)
│     at Module.require (node:internal/modules/cjs/loader:1234:19)
│     at require (node:internal/modules/helpers:176:18)
│     at Object.<anonymous> (/root/neuronek/node_modules/.pnpm/@sentry+profiling-node@0.2.2/node_modules/@sentry/profiling-node/…
│     at Module._compile (node:internal/modules/cjs/loader:1375:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
│     at Module.load (node:internal/modules/cjs/loader:1206:32)
│     at Module._load (node:internal/modules/cjs/loader:1022:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     '/root/neuronek/node_modules/.pnpm/@sentry+profiling-node@0.2.2/node_modules/@sentry/profiling-node/scripts/check-build.js'
│   ]
│ }
│ Node.js v21.5.0
└─ Failed in 6.6s at /root/neuronek/node_modules/.pnpm/@sentry+profiling-node@0.2.2/node_modules/@sentry/profiling-node
 ELIFECYCLE  Command failed with exit code 1.
`

Can you tell me if this is an actual issue with the codebase, or if I'm being a bit dense. I'm not the best with TypeScript but I'm a Solutions/Sales Engineer that does a lot of API work by trade and I'd love to help with this project when I'm not working. Don't want to bang my head against the wall if this is a dependency issue that you may be far more familiar with.

**Comment by keinsell** [comment]
Oh, that sucks. Sorry for inconvenience but there project was a little dead over past year and I was not aware I left it with build issues - personally I'm coming back to it at the middle of April so I'll let you know when issue will be fixed.

**Comment by keinsell** [comment]
Hi again, I've decided to reactivate the project and put it to the public - since repository is still kinda messy clutter I recommend using https://neuronek.up.railway.app/reference for the production-like data and the https://neuronek-qp8iosfsm-0x4b696973656c6c.vercel.app/ingestions for the preview what's the status of the front-end application. It's far from being functional yet, however with putting enough time into this I think with the end of month I would have working MVP.

**Comment by dattmavis** [comment]
This looks really great. I'll have some time next weekend to play with it a bit. Thanks for waking it from the dead!On May 4, 2024 1:31 PM, Jakub Olan ***@***.***> wrote:
Hi again, I've decided to reactivate the project and put it to the public - since repository is still kinda messy clutter I recommend using https://neuronek.up.railway.app/reference for the production-like data and the https://neuronek-qp8iosfsm-0x4b696973656c6c.vercel.app/ingestions for the preview what's the status of the front-end application. It's far from being functional yet, however with putting enough time into this I think with the end of month I would have working MVP.
